In [56]:
import pandas as pd

In [57]:
import numpy as np

In [58]:
aa = pd.read_csv("C:/Users/kanni/Downloads/archive (1)/cars.csv")

In [59]:
aa.head()

,car name,price,engine_capacity,cylinder,horse_power,top_speed,seats,brand,country
0,Fiat 500e 2021 La Prima,TBD,0.0,"N/A, Electric",Single,Automatic,150,fiat,ksa
1,Peugeot Traveller 2021 L3 VIP,"SAR 140,575",2.0,4,180,8 Seater,8.8,peugeot,ksa
2,Suzuki Jimny 2021 1.5L Automatic,"SAR 98,785",1.5,4,102,145,4 Seater,suzuki,ksa
3,Ford Bronco 2021 2.3T Big Bend,"SAR 198,000",2.3,4,420,4 Seater,7.5,ford,ksa
4,Honda HR-V 2021 1.8 i-VTEC LX,Orangeburst Metallic,1.8,4,140,190,5 Seater,honda,ksa

In [60]:
aa.tail()

,car name,price,engine_capacity,cylinder,horse_power,top_speed,seats,brand,country
6303,Bentley Mulsanne 2021 6.75L V8 Extended Wheelbase,DISCONTINUED,6.8,8,505,296,5 Seater,bentley,uae
6304,Ferrari SF90 Stradale 2021 4.0T V8 Plug-in-Hybrid,"AED 1,766,100",4.0,8,25,800,Automatic,ferrari,uae
6305,Rolls Royce Wraith 2021 6.6L Base,"AED 1,400,000",6.6,12,624,250,4 Seater,rolls-royce,uae
6306,Lamborghini Aventador S 2021 6.5L V12 Coupe,"AED 1,650,000",6.5,NaN,740,350,2 Seater,lamborghini,uae
6307,Bentley Mulsanne 2021 6.75L V8 Speed,DISCONTINUED,6.8,8,530,305,5 Seater,bentley,uae

In [61]:
aa.size

56772

In [62]:
print(aa.size)

56772

In [63]:
aa.shape

(6308, 9)

In [64]:
aa.columns

Index(['car name', 'price', 'engine_capacity', 'cylinder', 'horse_power',
       'top_speed', 'seats', 'brand', 'country'],
      dtype='str')

In [65]:
aa.isnull().sum()

car name             0
price                0
engine_capacity      0
cylinder           624
horse_power          0
top_speed            0
seats                0
brand                0
country              0
dtype: int64

In [66]:
len(aa)

6308

In [67]:
print(aa['cylinder'].mode())

0    4
Name: cylinder, dtype: str

In [68]:
aa['cylinder'] = aa['cylinder'].fillna(aa['cylinder'].mode()[0])

In [69]:
aa.isnull().sum()

car name           0
price              0
engine_capacity    0
cylinder           0
horse_power        0
top_speed          0
seats              0
brand              0
country            0
dtype: int64

In [70]:
aa.head()

,car name,price,engine_capacity,cylinder,horse_power,top_speed,seats,brand,country
0,Fiat 500e 2021 La Prima,TBD,0.0,"N/A, Electric",Single,Automatic,150,fiat,ksa
1,Peugeot Traveller 2021 L3 VIP,"SAR 140,575",2.0,4,180,8 Seater,8.8,peugeot,ksa
2,Suzuki Jimny 2021 1.5L Automatic,"SAR 98,785",1.5,4,102,145,4 Seater,suzuki,ksa
3,Ford Bronco 2021 2.3T Big Bend,"SAR 198,000",2.3,4,420,4 Seater,7.5,ford,ksa
4,Honda HR-V 2021 1.8 i-VTEC LX,Orangeburst Metallic,1.8,4,140,190,5 Seater,honda,ksa

In [71]:
aa.tail()

,car name,price,engine_capacity,cylinder,horse_power,top_speed,seats,brand,country
6303,Bentley Mulsanne 2021 6.75L V8 Extended Wheelbase,DISCONTINUED,6.8,8,505,296,5 Seater,bentley,uae
6304,Ferrari SF90 Stradale 2021 4.0T V8 Plug-in-Hybrid,"AED 1,766,100",4.0,8,25,800,Automatic,ferrari,uae
6305,Rolls Royce Wraith 2021 6.6L Base,"AED 1,400,000",6.6,12,624,250,4 Seater,rolls-royce,uae
6306,Lamborghini Aventador S 2021 6.5L V12 Coupe,"AED 1,650,000",6.5,4,740,350,2 Seater,lamborghini,uae
6307,Bentley Mulsanne 2021 6.75L V8 Speed,DISCONTINUED,6.8,8,530,305,5 Seater,bentley,uae

In [72]:
aa.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
6303    False
6304    False
6305    False
6306    False
6307    False
Length: 6308, dtype: bool

In [73]:
aa.duplicated().sum()

np.int64(16)

In [74]:
newvar = aa.drop_duplicates()

In [75]:
aa.duplicated().sum()

np.int64(16)

In [76]:
print(aa.duplicated().sum())

16

In [77]:
file1 = pd.read_csv("C:/Users/kanni/Downloads/load_forecasting_dataset_corrected.csv")

In [78]:
file1["Date"] = pd.to_datetime(file1["Timestamp"] ,errors = "coerce")

In [79]:
file1.head()

,Timestamp,Temperature (°C),Humidity (%),Wind Speed (m/s),Rainfall (mm),Solar Irradiance (W/m²),GDP (LKR),Per Capita Energy Use (kWh),Electricity Price (LKR/kWh),Day of Week,Hour of Day,Month,Season,Public Event,Load Demand (kW),Date
0,1/1/2020 0:00,28.993428,75.011269,1.053861,4.140513,185.892561,925.621430,502.915605,20.454440,2,0,1,Summer,0,1599.342831,2020-01-01 00:00:00
1,1/1/2020 0:15,27.723471,77.024015,1.085152,9.446997,281.782650,1020.823521,497.286366,27.776449,2,0,1,Summer,0,1472.347140,2020-01-01 00:15:00
2,1/1/2020 0:30,29.295377,74.732958,3.363800,4.265813,328.942058,1028.847455,488.816292,21.097420,2,0,1,Summer,0,1629.537708,2020-01-01 00:30:00
3,1/1/2020 0:45,31.046060,87.615995,2.539148,1.038103,336.407064,937.963002,468.038834,26.032137,2,0,1,Summer,1,1804.605971,2020-01-01 00:45:00
4,1/1/2020 1:00,27.531693,79.709858,1.366819,4.201393,205.494256,934.477462,488.565716,27.079114,2,1,1,Summer,0,1453.169325,2020-01-01 01:00:00

In [80]:
aa.loc[0:5,['car name', 'cylinder']]

                           car name       cylinder
0           Fiat 500e 2021 La Prima  N/A, Electric
1     Peugeot Traveller 2021 L3 VIP              4
2  Suzuki Jimny 2021 1.5L Automatic              4
3    Ford Bronco 2021 2.3T Big Bend              4
4     Honda HR-V 2021 1.8 i-VTEC LX              4
5     Honda HR-V 2021 1.8 i-VTEC EX              4

In [81]:
aa.iloc[0:5, 0:3]

                           car name                 price engine_capacity
0           Fiat 500e 2021 La Prima                   TBD             0.0
1     Peugeot Traveller 2021 L3 VIP           SAR 140,575             2.0
2  Suzuki Jimny 2021 1.5L Automatic            SAR 98,785             1.5
3    Ford Bronco 2021 2.3T Big Bend           SAR 198,000             2.3
4     Honda HR-V 2021 1.8 i-VTEC LX  Orangeburst Metallic             1.8

In [82]:
file1[file1["Month"] <2]

,Timestamp,Temperature (°C),Humidity (%),Wind Speed (m/s),Rainfall (mm),Solar Irradiance (W/m²),GDP (LKR),Per Capita Energy Use (kWh),Electricity Price (LKR/kWh),Day of Week,Hour of Day,Month,Season,Public Event,Load Demand (kW),Date
0,1/1/2020 0:00,28.993428,75.011269,1.053861,4.140513,185.892561,925.621430,502.915605,20.454440,2,0,1,Summer,0,1599.342831,2020-01-01 00:00:00
1,1/1/2020 0:15,27.723471,77.024015,1.085152,9.446997,281.782650,1020.823521,497.286366,27.776449,2,0,1,Summer,0,1472.347140,2020-01-01 00:15:00
2,1/1/2020 0:30,29.295377,74.732958,3.363800,4.265813,328.942058,1028.847455,488.816292,21.097420,2,0,1,Summer,0,1629.537708,2020-01-01 00:30:00
3,1/1/2020 0:45,31.046060,87.615995,2.539148,1.038103,336.407064,937.963002,468.038834,26.032137,2,0,1,Summer,1,1804.605971,2020-01-01 00:45:00
4,1/1/2020 1:00,27.531693,79.709858,1.366819,4.201393,205.494256,934.477462,488.565716,27.079114,2,1,1,Summer,0,1453.169325,2020-01-01 01:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
178363,1/31/2025 22:45,25.831123,87.245980,3.264956,10.393843,241.490562,1012.761324,557.454830,18.942573,4,22,1,Summer,0,1283.112288,2025-01-31 22:45:00
178364,1/31/2025 23:00,27.307472,77.094269,2.709711,0.078873,270.406230,971.758036,524.024450,30.233761,4,23,1,Summer,0,1430.747167,2025-01-31 23:00:00
178365,1/31/2025 23:15,26.645624,81.098666,2.876612,0.816193,262.282396,967.834951,513.823874,26.374745,4,23,1,Summer,0,1364.562420,2025-01-31 23:15:00
178366,1/31/2025 23:30,27.284299,79.158592,0.618708,5.181867,217.430447,976.479107,510.539473,28.524837,4,23,1,Summer,0,1428.429911,2025-01-31 23:30:00
178367,1/31/2025 23:45,30.388087,80.792514,2.511956,5.296777,255.163624,1069.533312,530.115511,27.012110,4,23,1,Summer,0,1738.808690,2025-01-31 23:45:00

In [83]:
file1[(file1['Month'] >1)&(file1["Day of Week"]<10)]

,Timestamp,Temperature (°C),Humidity (%),Wind Speed (m/s),Rainfall (mm),Solar Irradiance (W/m²),GDP (LKR),Per Capita Energy Use (kWh),Electricity Price (LKR/kWh),Day of Week,Hour of Day,Month,Season,Public Event,Load Demand (kW),Date
2976,2/1/2020 0:00,30.527413,80.570610,1.201059,3.158959,209.789802,920.128838,478.151255,22.759657,5,0,2,Summer,0,1752.741336,2020-02-01 00:00:00
2977,2/1/2020 0:15,26.307368,77.600305,4.563859,4.682453,277.123182,935.605795,536.695041,20.340496,5,0,2,Summer,0,1330.736805,2020-02-01 00:15:00
2978,2/1/2020 0:30,29.086959,73.856954,2.614530,10.820194,275.525642,967.429538,475.251687,28.172905,5,0,2,Summer,0,1608.695876,2020-02-01 00:30:00
2979,2/1/2020 0:45,28.399621,79.957380,1.382259,4.224979,231.698880,1069.842424,508.948294,23.893897,5,0,2,Summer,0,1539.962087,2020-02-01 00:45:00
2980,2/1/2020 1:00,28.528040,77.278693,2.307840,1.347936,243.751536,948.995344,511.278864,34.220010,5,1,2,Summer,0,1552.804016,2020-02-01 01:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189883,5/31/2025 22:45,27.433177,82.943227,1.564385,0.476854,214.276578,986.122824,487.823955,17.183842,5,22,5,Fall,0,1443.317681,2025-05-31 22:45:00
189884,5/31/2025 23:00,32.085127,84.159944,1.389473,0.309841,308.798749,970.258350,515.405431,29.773656,5,23,5,Fall,0,1908.512650,2025-05-31 23:00:00
189885,5/31/2025 23:15,27.620201,87.091108,2.722335,1.422315,282.487744,1007.429961,509.295868,24.883951,5,23,5,Fall,0,1462.020111,2025-05-31 23:15:00
189886,5/31/2025 23:30,29.378415,75.743129,2.317605,9.383305,246.291089,1019.239724,536.514530,27.765615,5,23,5,Fall,0,1637.841485,2025-05-31 23:30:00
189887,5/31/2025 23:45,27.737078,83.529497,0.914573,9.901955,299.088224,1020.425273,518.742211,15.496762,5,23,5,Fall,0,1473.707828,2025-05-31 23:45:00

In [84]:
file2 = pd.read_csv("C:/Users/kanni/Downloads/sales_data.csv")

In [85]:
file2["Sales"] = file2["Quantity"]*file2["UnitPrice"]

In [86]:
file2.head()

   OrderID        Date     Product     Category  Quantity  UnitPrice  Sales
0     1031  2026-01-01  Smartphone  Electronics         3        800   2400
1     1100  2026-01-02  Headphones  Accessories         2        150    300
2     1028  2026-01-02      Laptop  Electronics         2       1200   2400
3     1089  2026-01-02      Laptop  Electronics         3       1200   3600
4     1023  2026-01-02      Tablet  Electronics         4        450   1800

In [88]:
file2.groupby("Category")["Sales"].min()

Category
Accessories    150
Electronics    450
Name: Sales, dtype: int64

In [89]:
file2.groupby("Category")["Sales"].count()

Category
Accessories    42
Electronics    58
Name: Sales, dtype: int64

In [90]:
from sklearn.preprocessing import LabelEncoder,OrdinalEncoder

In [91]:
ff = pd.read_csv("C:/Users/kanni/Downloads/Shopping_Customer_Dataset (1).csv")

In [92]:
newvar1 = LabelEncoder()

In [93]:
ff["Gendernew"] = newvar1.fit_transform(ff["Gender"])

In [94]:
ff.head()

,Gender,Product_Category,Payment_Method,Membership_Level,City,Customer_Rating,Total_Items,Gendernew
0,Male,Beauty,Cash,Premium,Chicago,4.6,8,1
1,Female,Home & Kitchen,PayPal,Bronze,Chicago,4.2,2,0
2,Female,Sports,Debit Card,Silver,Miami,3.7,9,0
3,Female,Electronics,Cash,Silver,New York,3.7,5,0
4,Male,Sports,PayPal,Silver,Los Angeles,4.8,10,1

In [95]:
ord = OrdinalEncoder(categories = [["Bronze", "Silver", "Gold","Premium"]])
ff["Membership_Level1"] = ord.fit_transform(ff[["Membership_Level"]])
ff.head()

,Gender,Product_Category,Payment_Method,Membership_Level,City,Customer_Rating,Total_Items,Gendernew,Membership_Level1
0,Male,Beauty,Cash,Premium,Chicago,4.6,8,1,3.0
1,Female,Home & Kitchen,PayPal,Bronze,Chicago,4.2,2,0,0.0
2,Female,Sports,Debit Card,Silver,Miami,3.7,9,0,1.0
3,Female,Electronics,Cash,Silver,New York,3.7,5,0,1.0
4,Male,Sports,PayPal,Silver,Los Angeles,4.8,10,1,1.0